version: "3.9"
services:
  verifier:
    image: eudi-verifier:dev-empty-ta
    pull_policy: never
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "http://localhost:8080"
      VERIFIER_CLIENTMETADATA_VPFORMATS_MSOMDOC_ENABLED: "true"
      VERIFIER_CLIENTMETADATA_VPFORMATS_SDJWTVC_ENABLED: "true"
      VERIFIER_JAR_SIGNING_KEY: "GenerateRandom"
